# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/hls_proj_2/vivado/addb/addb.cache/wt [current_project]
set_property parent.project_path C:/Users/hls_proj_2/vivado/addb/addb.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/hls_proj_2/matlab [current_project]
set_property ip_output_repo c:/Users/hls_proj_2/vivado/addb/addb.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/hdl/base_zynq_wrapper.vhd
add_files C:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/base_zynq.bd
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_processing_system7_0_0/base_zynq_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_blk_mem_gen_0_0/base_zynq_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_axi_bram_ctrl_0_0/base_zynq_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_rst_ps7_0_50M_0/base_zynq_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_addb_0_0/constrs/addb.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_0/base_zynq_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/ip/base_zynq_auto_pc_1/base_zynq_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/base_zynq_ooc.xdc]
set_property is_locked true [get_files C:/Users/hls_proj_2/vivado/addb/addb.srcs/sources_1/bd/base_zynq/base_zynq.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top base_zynq_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef base_zynq_wrapper.dcp

catch { report_utilization -file base_zynq_wrapper_utilization_synth.rpt -pb base_zynq_wrapper_utilization_synth.pb }
